name: Ollama Server with Static ngrok Domain

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: 'Job ID for tracking'
        required: false
        default: ''
      callback_url:
        description: 'Callback URL for status updates'
        required: false
        default: ''
      kv_namespace_id:
        description: 'Cloudflare KV Namespace ID'
        required: false
        default: ''
      ngrok_domain:
        description: 'Static ngrok domain (e.g., your-domain.ngrok-free.app)'
        required: false
        default: ''

env:
  OLLAMA_HOST: 0.0.0.0:11543
  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
  NGROK_STATIC_DOMAIN: ${{ github.event.inputs.ngrok_domain || secrets.NGROK_STATIC_DOMAIN }}
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
  GGITHUB_TOKEN: ${{ secrets.GGITHUB_TOKEN }}

jobs:
  ollama-server:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: Trigger next workflow run
        if: always()
        run: |
          echo "🔄 Triggering next workflow run..."
          
          # Trigger workflow via GitHub API
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GGITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"${{ github.ref_name }}", "inputs":{"restart_reason":"auto_restart_after_'${{ env.RUNTIME_HOURS }}'h"}}' \
            || echo "⚠️  Failed to trigger next run - manual restart may be needed"
          
          echo "✅ Next workflow triggered successfully"

